# Generated by Django 4.0.4 on 2022-06-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_experience_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='joptype',
            new_name='jobtype',
        ),
    ]
