# Generated by Django 4.0.4 on 2022-06-23 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_profile_address_remove_profile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='image',
        ),
    ]
